namespace YVR.Core
{
    public enum YVRPlaneDetectorOrientation
    {
        XR_PLANE_DETECTOR_ORIENTATION_HORIZONTAL_UPWARD_EXT = 0,
        XR_PLANE_DETECTOR_ORIENTATION_HORIZONTAL_DOWNWARD_EXT = 1,
        XR_PLANE_DETECTOR_ORIENTATION_VERTICAL_EXT = 2,
        XR_PLANE_DETECTOR_ORIENTATION_ARBITRARY_EXT = 3,
        XR_PLANE_DETECTOR_ORIENTATION_MAX_ENUM_EXT = 0x7FFFFFFF
    }
}