namespace YVR.Core
{
    public enum YVRPlaneDetectorSemanticType
    {
        XR_PLANE_DETECTOR_SEMANTIC_TYPE_UNDEFINED_EXT = 0,
        XR_PLANE_DETECTOR_SEMANTIC_TYPE_CEILING_EXT = 1,
        XR_PLANE_DETECTOR_SEMANTIC_TYPE_FLOOR_EXT = 2,
        XR_PLANE_DETECTOR_SEMANTIC_TYPE_WALL_EXT = 3,
        XR_PLANE_DETECTOR_SEMANTIC_TYPE_PLATFORM_EXT = 4,
        XR_PLANE_DETECTOR_SEMANTIC_TYPE_MAX_ENUM_EXT = 0x7FFFFFFF
    }
}