namespace YVR.Core
{
    public enum YVRPlaneDetectorState
    {
        XR_PLANE_DETECTION_STATE_NONE_EXT = 0,
        XR_PLANE_DETECTION_STATE_PENDING_EXT = 1,
        XR_PLANE_DETECTION_STATE_DONE_EXT = 2,
        XR_PLANE_DETECTION_STATE_ERROR_EXT = 3,
        XR_PLANE_DETECTION_STATE_FATAL_EXT = 4,
        XR_PLANE_DETECTION_STATE_MAX_ENUM_EXT = 0x7FFFFFFF
    }
}